### ISSUE TITLE
bug bbq website draft

### ISSUE THREAD

**Issue by katieannemills** [katieannemills/SWC-bug-bbq#1]
cc @ttimbers @gvwilson 

Here's a website draft - any comments / requests? I will gift this repo to swc once we're ready to launch.

Tiffany, one notable difference is that I opted to include live sites, even though we were kind of on the fence about this - I figure we can keep overhead down by simply sticking a pin on the map and leaving the rest to the local hosts - no reason not to?

**Comment by gvwilson** [comment]
Thanks, but why a separate website?  Wouldn't a blog post (updated as 
needed) on the SWC site do?
Thx,
G

**Comment by katieannemills** [comment]
@gvwilson would you like chocolate ice cream, or vanilla? The correct answer is _both_ :)

@ttimbers has a blog post landing in the next week or two to kick off promotion in parallel with a dedicated website.

**Comment by gvwilson** [comment]
Fire away.
thx
G

**Comment by ttimbers** [comment]
Looks great @BillMills! And although we were on the fence about the live sites, I like the way you've set it up as an option. Nice work!

**Comment by ttimbers** [comment]
@gvwilson - I will have a blog post ready by the end of the week. I had hoped to get to it sooner, but I have a talk to prepare for, and give on Thursday, and it's consuming my week...
